# Generated by Django 5.1.11 on 2026-01-23 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_subscriptionsprice_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionsprice',
            options={'ordering': ['order', 'featured', '-updated']},
        ),
    ]
