# Generated by Django 5.1.11 on 2026-01-23 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_alter_subscriptions_options_subscriptions_featured_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionsprice',
            options={'ordering': ['subscription__order', 'order', 'featured', '-updated']},
        ),
    ]
