# Generated by Django 5.1.11 on 2026-01-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_rename_subscriptions_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionsprice',
            name='features',
            field=models.TextField(blank=True, help_text='Feature for pricing, seperated by new line', null=True),
        ),
    ]
