# Generated by Django 5.1.11 on 2026-01-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_subscriptionsprice_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionsprice',
            name='features',
        ),
        migrations.AddField(
            model_name='subscription',
            name='features',
            field=models.TextField(blank=True, help_text='Feature for pricing, seperated by new line', null=True),
        ),
    ]
